export const codes = [
  { value: "DTAA", label: "ASSIGNMENT OF SUB AGREEMENT OF SALE" },
  { value: "DTAB", label: "ASSIGNMENT OF SUB LEASE" },
  { value: "DTAC", label: "ASSIGNMENT OF COMMERCIAL LEASE" },
  { value: "DTAD", label: "ADMINISTRATORS DEED" },
  { value: "DTAF", label: "AFFIDAVIT" },
  { value: "DTAG", label: "AGREEMENT OF SALE" },
  { value: "DTAH", label: "ASSESSOR SALES HISTORY" },
  { value: "DTAL", label: "QUIT CLAIM ARM'S LENGTH FOR NE STATES" },
  { value: "DTAO", label: "ASSIGNMENT OF DEED OF TRUST" },
  { value: "DTAR", label: "ASSIGNMENT OF AGREEMENT OF SALE" },
  { value: "DTAS", label: "ASSIGNMENT OF DEED" },
  { value: "DTAT", label: "AFFIDAVIT OF TRUST OR TRUST AGREEMENT" },
  { value: "DTAU", label: "ASSIGNMENT OF SUB COMMERCIAL LEASE" },
  { value: "DTBD", label: "BENEFICIARY DEED" },
  { value: "DTBK", label: "BANKRUPTCY" },
  { value: "DTBS", label: "BARGAIN AND SALE DEED" },
  { value: "DTCA", label: "COMMISSIONERS ASSIGNMENT OF LEASE" },
  { value: "DTCD", label: "CONDOMINIUM DEED" },
  { value: "DTCE", label: "COMMITTEE" },
  { value: "DTCF", label: "ONE OF COMMITTEE, STRICT FORECLOSURE, SHERIFF, OR REDEMPTION DEEDS" },
  { value: "DTCH", label: "CASH SALE DEED" },
  { value: "DTCL", label: "COMMERCIAL LEASE" },
  { value: "DTCM", label: "COMMISSIONERS DEED" },
  { value: "DTCN", label: "CANCELLATION OF AGREEMENT OF SALE" },
  { value: "DTCO", label: "CONSERVATORS DEED" },
  { value: "DTCP", label: "CORPORATION DEED" },
  { value: "DTCR", label: "CORRECTION DEED" },
  { value: "DTCS", label: "CONTRACT SALE" },
  { value: "DTCT", label: "CERTIFICATE OF TRANSFER" },
  { value: "DTCV", label: "CONVEYANCE" },
  { value: "DTDB", label: "DEED OF DISTRIBUTION" },
  { value: "DTDC", label: "DECLARATION" },
  { value: "DTDD", label: "TRANSFER ON DEATH DEED" },
  { value: "DTDE", label: "DEED" },
  { value: "DTDG", label: "DEED OF GUARDIAN" },
  { value: "DTDJ", label: "AFFIDAVIT OF DEATH OF JOINT TENANT" },
  { value: "DTDL", label: "DEED IN LIEU OF FORECLOSURE" },
  { value: "DTDP", label: "DUAL PURPOSE DOCUMENT" },
  { value: "DTDS", label: "DISTRESS SALE" },
  { value: "DTDT", label: "AFFIDAVIT OF DEATH" },
  { value: "DTDX", label: "TAX DEED" },
  { value: "DTEC", label: "EXCHANGE" },
  { value: "DTES", label: "LIFE ESTATE" },
  { value: "DTEX", label: "EXECUTORS DEED" },
  { value: "DTFC", label: "FORECLOSURE" },
  { value: "DTFD", label: "FIDUCIARY DEED" },
  { value: "DTFP", label: "CERTIFICATE OF PURCHASE" },
  { value: "DTGD", label: "GRANT DEED" },
  { value: "DTGE", label: "ONE OF CONSERVATOR, EXECUTOR, GUARDIAN, GRANT, TAX COLLECTOR, OR TRUSTEE DEEDS" },
  { value: "DTGF", label: "GIFT DEED" },
  { value: "DTGR", label: "GROUND LEASE" },
  { value: "DTID", label: "INDIVIDUAL DEED" },
  { value: "DTIT", label: "INTRAFAMILY TRANSFER" },
  { value: "DTJT", label: "JOINT TENANCY DEED" },
  { value: "DTLA", label: "LEGAL ACTION/COURT ORDER" },
  { value: "DTLC", label: "LEASEHOLD CONV. WITH AGREEM. OF SALE (FEE PURCHASE)" },
  { value: "DTLD", label: "LAND CONTRACT" },
  { value: "DTLE", label: "LEASE" },
  { value: "DTLH", label: "ASSIGNMENT OF LEASE (LEASEHOLD SALE)" },
  { value: "DTLS", label: "LEASEHOLD CONV. W/AN AGREEMENT OF SALE" },
  { value: "DTLT", label: "LAND COURT" },
  { value: "DTLW", label: "LIMITED WARRANTY DEED" },
  { value: "DTMD", label: "SPECIAL MASTER DEED" },
  { value: "DTMF", label: "MANUF HOUSING" },
  { value: "DTMG", label: "MORTGAGEE" },
  { value: "DTML", label: "MORTGAGE LIEN" },
  { value: "DTMN", label: "MUNICIPAL" },
  { value: "DTMO", label: "LOAN MODIFICATION" },
  { value: "DTMX", label: "LOAN MODIFICATION, CONSOLIDATION AND EXTENSION" },
  { value: "DTOT", label: "OTHER" },
  { value: "DTPA", label: "PUBLIC ACTION" },
  { value: "DTPD", label: "PARTNERSHIP DEED" },
  { value: "DTPR", label: "PERSONAL REPRESENTATIVE DEED" },
  { value: "DTQC", label: "QUIT CLAIM DEED" },
  { value: "DTR1", label: "LOAN 1 (ONLY) IS A REVERSE MORTGAGE" },
  { value: "DTR2", label: "LOAN 2 (ONLY) IS A REVERSE MORTGAGE" },
  { value: "DTR3", label: "LOAN 3 (ONLY) IS A REVERSE MORTGAGE" },
  { value: "DTR4", label: "LOANS 1 AND 2 ARE BOTH REVERSE MORTGAGES" },
  { value: "DTR5", label: "LOANS 1 AND 3 ARE BOTH REVERSE MORTGAGES" },
  { value: "DTR6", label: "LOANS 1, 2 AND 3 ARE ALL REVERSE MORTGAGES" },
  { value: "DTR7", label: "LOANS 2 AND 3 ARE BOTH REVERSE MORTGAGES" },
  { value: "DTRA", label: "RELEASE/SATIS. OF AGREM. OF SALE (FEE PROPERTY)" },
  { value: "DTRC", label: "RECEIVERS DEED" },
  { value: "DTRD", label: "REDEMPTION DEED" },
  { value: "DTRE", label: "COMBINE TABLE REO DEED" },
  { value: "DTRF", label: "REFEREE'S DEED - USED TO TRANSFER PROPERTY PURSUANT TO A FORECLOSURE SALE IN NEW YORK COUNTIES" },
  { value: "DTRL", label: "RELEASE/SATIS. OF AGREM. OF SALE (LEASEHOLD)" },
  { value: "DTRR", label: "RE-RECORDED DOCUMENT" },
  { value: "DTRS", label: "REO SALE (REO OUT)" },
  { value: "DTSA", label: "SUB AGREEMENT OF SALE" },
  { value: "DTSC", label: "SUB COMMERCIAL LEASE" },
  { value: "DTSD", label: "SHERIFFS DEED" },
  { value: "DTSL", label: "SUB LEASE" },
  { value: "DTSS", label: "ASSUMPTION DEED" },
  { value: "DTST", label: "AFFIDAVIT DEATH OF TRUSTEE/SUCCESSOR TRUSTEE" },
  { value: "DTSV", label: "SURVIVORSHIP DEED" },
  { value: "DTSW", label: "SPECIAL WARRANTY DEED" },
  { value: "DTTC", label: "TAX COLLECTOR" },
  { value: "DTTD", label: "TRUSTEES DEED" },
  { value: "DTTR", label: "DEED OF TRUST" },
  { value: "DTVL", label: "VENDERS LIEN" },
  { value: "DTWD", label: "WARRANTY DEED" },
  { value: "DTXX", label: "TRANSACTION HISTORY RECORD" },
  { value: "XXXX", label: "Unknown" },
];
